"""Initial migration

Revision ID: 73d647d8385f
Revises: 
Create Date: 2026-03-09 06:57:27.961773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73d647d8385f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('activity_logs_user_id_fkey', 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'])
    op.drop_column('activity_logs', 'metadata')
    op.alter_column('analysis_runs', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_analysis_project', table_name='analysis_runs')
    op.drop_constraint('analysis_runs_project_id_fkey', 'analysis_runs', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_runs', 'projects', ['project_id'], ['id'])
    op.alter_column('contradictions', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_contradictions_analysis', table_name='contradictions')
    op.drop_constraint('contradictions_analysis_id_fkey', 'contradictions', type_='foreignkey')
    op.create_foreign_key(None, 'contradictions', 'analysis_runs', ['analysis_id'], ['id'])
    op.add_column('experimental_protocols', sa.Column('title', sa.Text(), nullable=True))
    op.alter_column('experimental_protocols', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('experimental_protocols', 'independent_variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('experimental_protocols', 'dependent_variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('experimental_protocols', 'control_variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_protocols_analysis', table_name='experimental_protocols')
    op.drop_constraint('experimental_protocols_analysis_id_fkey', 'experimental_protocols', type_='foreignkey')
    op.create_foreign_key(None, 'experimental_protocols', 'analysis_runs', ['analysis_id'], ['id'])
    op.alter_column('exports', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('exports_analysis_id_fkey', 'exports', type_='foreignkey')
    op.create_foreign_key(None, 'exports', 'analysis_runs', ['analysis_id'], ['id'])
    op.add_column('paper_chunks', sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('paper_chunks', 'paper_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_chunks_paper', table_name='paper_chunks')
    op.drop_constraint('paper_chunks_paper_id_fkey', 'paper_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'paper_chunks', 'research_papers', ['paper_id'], ['id'])
    op.drop_column('paper_chunks', 'metadata')
    op.add_column('projects', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_projects_user', table_name='projects')
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.drop_column('projects', 'user_id')
    op.alter_column('reasoning_traces', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reasoning_traces', 'source_chunks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_reasoning_analysis', table_name='reasoning_traces')
    op.drop_constraint('reasoning_traces_analysis_id_fkey', 'reasoning_traces', type_='foreignkey')
    op.create_foreign_key(None, 'reasoning_traces', 'analysis_runs', ['analysis_id'], ['id'])
    op.alter_column('research_gaps', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('research_gaps_analysis_id_fkey', 'research_gaps', type_='foreignkey')
    op.create_foreign_key(None, 'research_gaps', 'analysis_runs', ['analysis_id'], ['id'])
    op.alter_column('research_papers', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_papers_project', table_name='research_papers')
    op.drop_constraint('research_papers_project_id_fkey', 'research_papers', type_='foreignkey')
    op.create_foreign_key(None, 'research_papers', 'projects', ['project_id'], ['id'])
    op.add_column('users', sa.Column('hashed_password', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'research_papers', type_='foreignkey')
    op.create_foreign_key('research_papers_project_id_fkey', 'research_papers', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_papers_project', 'research_papers', ['project_id'], unique=False)
    op.alter_column('research_papers', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'research_gaps', type_='foreignkey')
    op.create_foreign_key('research_gaps_analysis_id_fkey', 'research_gaps', 'analysis_runs', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.alter_column('research_gaps', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'reasoning_traces', type_='foreignkey')
    op.create_foreign_key('reasoning_traces_analysis_id_fkey', 'reasoning_traces', 'analysis_runs', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_reasoning_analysis', 'reasoning_traces', ['analysis_id'], unique=False)
    op.alter_column('reasoning_traces', 'source_chunks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('reasoning_traces', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('projects', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_projects_user', 'projects', ['user_id'], unique=False)
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'owner_id')
    op.add_column('paper_chunks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'paper_chunks', type_='foreignkey')
    op.create_foreign_key('paper_chunks_paper_id_fkey', 'paper_chunks', 'research_papers', ['paper_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_chunks_paper', 'paper_chunks', ['paper_id'], unique=False)
    op.alter_column('paper_chunks', 'paper_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('paper_chunks', 'extra_metadata')
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.create_foreign_key('exports_analysis_id_fkey', 'exports', 'analysis_runs', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exports', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'experimental_protocols', type_='foreignkey')
    op.create_foreign_key('experimental_protocols_analysis_id_fkey', 'experimental_protocols', 'analysis_runs', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_protocols_analysis', 'experimental_protocols', ['analysis_id'], unique=False)
    op.alter_column('experimental_protocols', 'control_variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('experimental_protocols', 'dependent_variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('experimental_protocols', 'independent_variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('experimental_protocols', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('experimental_protocols', 'title')
    op.drop_constraint(None, 'contradictions', type_='foreignkey')
    op.create_foreign_key('contradictions_analysis_id_fkey', 'contradictions', 'analysis_runs', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_contradictions_analysis', 'contradictions', ['analysis_id'], unique=False)
    op.alter_column('contradictions', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'analysis_runs', type_='foreignkey')
    op.create_foreign_key('analysis_runs_project_id_fkey', 'analysis_runs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_analysis_project', 'analysis_runs', ['project_id'], unique=False)
    op.alter_column('analysis_runs', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('activity_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key('activity_logs_user_id_fkey', 'activity_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('activity_logs', 'extra_metadata')
    # ### end Alembic commands ###
